FROM php:7.2.2-fpm

RUN apt-get update && apt-get install --yes --no-install-recommends libpq-dev git unzip curl sendmail libfreetype6-dev libjpeg62-turbo-dev libpng-dev && docker-php-ext-install pdo_pgsql pdo_mysql && \
docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/  &&  \
docker-php-ext-install gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer;

RUN apt-get install -y cron htop nano

RUN chmod +x -R /var/www/html

RUN pecl install xdebug

RUN docker-php-ext-enable xdebug